### ISSUE TITLE
imoClass Regex maybe incorrect?

### ISSUE THREAD

**Issue by cmsdroff** [dcsaorg/DCSA-OpenAPI#153]
Hi, 

For the `imoClass` noted here https://app.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/3.1.0#/components/schemas/imoClass (apologies can't find in Github)

I'm not sure if the `imoClass` should enforce the `.x` part of the value, we very often see the IMO class being passed as value `9` (miscellaneous) in movements and DG Notes which fails the regex specified in the class below, whilst class 9 (and others) can be split to a `.x` value it is not always that common looking at the DG Notes, and also the placard's used to identify the hazard.

So I'm questioning if it should be allowed to use just `9` or will it be enforced to use `9.1` or `9.2`

also if this should be an enum to identify only specific and valid classes as you cannot have `9.6` for example?

We have had to override and remove the `pattern` from the schema to start using the DCSA schemas in the project, and left an open ticket relating to this one, welcome your thoughts.

```
imoClass:
      type: string
      pattern: '^[1-9]\.[1-9][A-Z]?$'
      description: |
        The hazard class code of the referenced dangerous goods according to the specified regulation.
      example: '1.4S'
```
